# Generated by Django 5.2.14 on 2026-05-21 11:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('mxik', models.CharField(blank=True, db_index=True, max_length=10)),
                ('unit', models.CharField(max_length=20)),
                ('current_stock', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('min_stock', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('avg_price', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('last_received_at', models.DateTimeField(blank=True, null=True)),
                ('org', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tenants.org')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.store')),
            ],
            options={
                'db_table': 'products_product',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('kirim', 'Kirim'), ('chiqim', 'Chiqim'), ('inventarizatsiya', 'Inventarizatsiya'), ('doc_approve', 'Hujjat tasdiqi')], max_length=20)),
                ('delta', models.DecimalField(decimal_places=3, max_digits=14)),
                ('before', models.DecimalField(decimal_places=3, max_digits=14)),
                ('after', models.DecimalField(decimal_places=3, max_digits=14)),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('document_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('org', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tenants.org')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='products.product')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.store')),
            ],
            options={
                'db_table': 'products_stock_movement',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['store', 'name'], name='products_pr_store_i_ec6700_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['store', 'mxik'], name='products_pr_store_i_3a00d0_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['product', '-created_at'], name='products_st_product_6308ea_idx'),
        ),
    ]
