# Generated by Django 5.2.14 on 2026-05-21 11:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone', models.CharField(db_index=True, max_length=15, unique=True)),
                ('full_name', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'accounts_user',
            },
        ),
        migrations.CreateModel(
            name='OTPCode',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone', models.CharField(db_index=True, max_length=15)),
                ('code_hash', models.CharField(max_length=128)),
                ('purpose', models.CharField(choices=[('login', 'Login'), ('register', 'Register'), ('reset', 'Password reset')], max_length=20)),
                ('expires_at', models.DateTimeField()),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('attempts', models.IntegerField(default=0)),
                ('requester_ip', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'db_table': 'accounts_otp_code',
                'indexes': [models.Index(fields=['phone', 'purpose', 'consumed_at'], name='accounts_ot_phone_fa23e4_idx')],
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('portal', models.CharField(choices=[('store', "Chakana do'kon"), ('supplier', 'Distribyutor'), ('soliq', 'Soliq')], default='store', max_length=10)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('role', models.CharField(choices=[('admin', 'Administrator'), ('omborchi', 'Omborchi'), ('buxgalter', 'Buxgalter'), ('kassir', 'Kassir'), ('auditor', 'Auditor'), ('firma', 'Firma operatori'), ('supplier_admin', 'Distribyutor admin'), ('supplier_sales', 'Sotuv menejer'), ('supplier_logistics', 'Logistika'), ('supplier_buxgalter', 'Distribyutor buxgalter'), ('soliq_inspector', 'Inspektor'), ('soliq_admin', 'Soliq admin')], max_length=30)),
                ('status', models.CharField(choices=[('active', 'Faol'), ('blocked', 'Bloklangan'), ('pending', 'Kutilmoqda')], default='pending', max_length=20)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='tenants.store')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'accounts_membership',
                'indexes': [models.Index(fields=['portal', 'tenant_id', 'status'], name='accounts_me_portal_5ba4a0_idx'), models.Index(fields=['user', 'portal'], name='accounts_me_user_id_999efd_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('portal', 'store'), ('store__isnull', False)), models.Q(('portal', 'store'), _negated=True), _connector='OR'), name='membership_store_fk_when_store_portal')],
                'unique_together': {('user', 'portal', 'tenant_id')},
            },
        ),
    ]
