# Generated by Django 5.2.14 on 2026-05-21 11:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductRow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('raw_name', models.CharField(max_length=500)),
                ('mxik_code', models.CharField(blank=True, max_length=10)),
                ('mxik_name', models.CharField(blank=True, max_length=500)),
                ('mxik_confidence', models.FloatField(default=0)),
                ('alternatives', models.JSONField(blank=True, default=list)),
                ('unit', models.CharField(max_length=20)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14)),
                ('price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('status', models.CharField(choices=[('matched', 'Mos kelgan'), ('new', 'Yangi'), ('ambiguous', 'Noaniq'), ('approved', 'Tasdiqlangan'), ('rejected', 'Rad etilgan')], default='new', max_length=20)),
                ('order_index', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'documents_product_row',
                'ordering': ('order_index', 'created_at'),
            },
        ),
        migrations.CreateModel(
            name='RetailDocument',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=50)),
                ('source', models.CharField(choices=[('didox', 'Didox'), ('excel', 'Excel'), ('pdf', 'PDF'), ('photo', 'Foto'), ('manual', "Qo'lda")], max_length=10)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Tahlil qilinmoqda'), ('review', "Ko'rib chiqilmoqda"), ('approved', 'Tasdiqlangan'), ('rejected', 'Rad etilgan'), ('duplicate', 'Dublikat')], default='pending', max_length=20)),
                ('review_count', models.IntegerField(default=0)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('dedup_hash', models.CharField(blank=True, db_index=True, max_length=64)),
            ],
            options={
                'db_table': 'documents_retail_document',
                'ordering': ('-created_at',),
            },
        ),
    ]
