# Generated by Django 5.2.14 on 2026-05-21 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0002_initial'),
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='retaildocument',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='suppliers.supplier'),
        ),
        migrations.AddField(
            model_name='productrow',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='documents.retaildocument'),
        ),
        migrations.AddIndex(
            model_name='retaildocument',
            index=models.Index(fields=['store', '-created_at'], name='documents_r_store_i_cbac7e_idx'),
        ),
        migrations.AddIndex(
            model_name='retaildocument',
            index=models.Index(fields=['store', 'status'], name='documents_r_store_i_2b46e3_idx'),
        ),
        migrations.AddIndex(
            model_name='productrow',
            index=models.Index(fields=['document', 'order_index'], name='documents_p_documen_a9f646_idx'),
        ),
        migrations.AddIndex(
            model_name='productrow',
            index=models.Index(fields=['status'], name='documents_p_status_67f084_idx'),
        ),
    ]
