# Generated by Django 5.2.14 on 2026-05-21 11:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('plan', models.CharField(choices=[('beta', 'Beta'), ('pro', 'Pro'), ('enterprise', 'Enterprise')], default='beta', max_length=20)),
                ('mxik_confidence_threshold', models.FloatField(default=0.85)),
            ],
            options={
                'db_table': 'tenants_store',
            },
        ),
        migrations.CreateModel(
            name='Org',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('stir', models.CharField(max_length=14, unique=True)),
            ],
            options={
                'db_table': 'tenants_org',
            },
        ),
        migrations.CreateModel(
            name='SoliqOffice',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('region', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'db_table': 'tenants_soliq_office',
            },
        ),
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='company', serialize=False, to='tenants.store')),
                ('stir', models.CharField(max_length=14, unique=True)),
                ('stir_verified', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=200)),
                ('activity', models.CharField(blank=True, max_length=200)),
                ('address', models.TextField(blank=True)),
                ('director', models.CharField(blank=True, max_length=200)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'db_table': 'tenants_company_info',
            },
        ),
        migrations.AddField(
            model_name='store',
            name='org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stores', to='tenants.org'),
        ),
    ]
