# Generated by Django 5.2.14 on 2026-05-21 11:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('stir', models.CharField(max_length=14)),
                ('verified', models.BooleanField(default=False)),
                ('soliq_last_checked', models.DateTimeField(blank=True, null=True)),
                ('org', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tenants.org')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.store')),
            ],
            options={
                'db_table': 'suppliers_supplier',
                'ordering': ('name',),
                'indexes': [models.Index(fields=['store', 'name'], name='suppliers_s_store_i_a29c7f_idx'), models.Index(fields=['store', 'verified'], name='suppliers_s_store_i_c655ca_idx')],
                'unique_together': {('store', 'stir')},
            },
        ),
    ]
