# Generated by Django 5.2.14 on 2026-05-21 11:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierCompany',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('stir', models.CharField(max_length=14, unique=True)),
                ('director', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('brand_type', models.CharField(choices=[('local', 'Mahalliy'), ('international', 'Xalqaro'), ('exclusive', 'Eksklyuziv')], default='local', max_length=20)),
                ('region', models.CharField(max_length=100)),
                ('fleet_size', models.PositiveIntegerField(default=0)),
                ('warehouse_address', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Supplier companies',
                'db_table': 'supplier_portal_company',
            },
        ),
        migrations.CreateModel(
            name='OutgoingInvoice',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('draft', 'Qoralama'), ('sent', 'Yuborilgan'), ('received', 'Qabul qilingan'), ('approved', 'Tasdiqlangan'), ('preparing', 'Tayyorlanmoqda'), ('delivering', 'Yetkazilmoqda'), ('delivered', 'Yetkazildi'), ('paid', "To'landi"), ('cancelled', 'Bekor qilindi')], default='draft', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('tracking_note', models.CharField(blank=True, max_length=300)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_invoices', to='supplier_portal.suppliercompany')),
            ],
            options={
                'db_table': 'supplier_portal_invoice',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='IncomingOrder',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('store_name', models.CharField(max_length=200)),
                ('number', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('accepted', 'Qabul qilindi'), ('rejected', 'Rad etildi'), ('fulfilled', 'Bajarildi')], default='pending', max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('rejection_reason', models.CharField(blank=True, max_length=300)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_orders', to='supplier_portal.suppliercompany')),
            ],
            options={
                'db_table': 'supplier_portal_incoming_order',
                'ordering': ('-requested_at',),
            },
        ),
        migrations.CreateModel(
            name='DeliveryRoute',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('driver_name', models.CharField(max_length=200)),
                ('vehicle_plate', models.CharField(max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('estimated_completion', models.DateTimeField(blank=True, null=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='supplier_portal.suppliercompany')),
            ],
            options={
                'db_table': 'supplier_portal_route',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='SupplierProduct',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('mxik', models.CharField(blank=True, max_length=10)),
                ('category', models.CharField(choices=[('ichimliklar', 'Ichimliklar'), ('oziq-ovqat', 'Oziq-ovqat'), ('sigaret', 'Sigaret'), ('maishiy', 'Maishiy'), ('kosmetika', 'Kosmetika'), ('boshqa', 'Boshqa')], default='boshqa', max_length=20)),
                ('unit', models.CharField(max_length=20)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('stock', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('monthly_sales', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('trend_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='supplier_portal.suppliercompany')),
            ],
            options={
                'db_table': 'supplier_portal_product',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='OutgoingInvoiceItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('mxik', models.CharField(blank=True, max_length=10)),
                ('unit', models.CharField(max_length=20)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14)),
                ('price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='supplier_portal.outgoinginvoice')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='supplier_portal.supplierproduct')),
            ],
            options={
                'db_table': 'supplier_portal_invoice_item',
            },
        ),
        migrations.CreateModel(
            name='IncomingOrderItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('mxik', models.CharField(blank=True, max_length=10)),
                ('unit', models.CharField(max_length=20)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14)),
                ('price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='supplier_portal.incomingorder')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='supplier_portal.supplierproduct')),
            ],
            options={
                'db_table': 'supplier_portal_incoming_order_item',
            },
        ),
        migrations.CreateModel(
            name='DemandSignal',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=200)),
                ('region', models.CharField(max_length=100)),
                ('district', models.CharField(blank=True, max_length=100)),
                ('weekly_volume', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('trend_percent', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('predicted_next_week', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('hotness', models.CharField(choices=[('rising', "O'sayotgan"), ('stable', 'Barqaror'), ('falling', 'Pasayayotgan')], default='stable', max_length=20)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demand_signals', to='supplier_portal.suppliercompany')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='supplier_portal.supplierproduct')),
            ],
            options={
                'db_table': 'supplier_portal_demand_signal',
            },
        ),
        migrations.CreateModel(
            name='SupplierStore',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('store_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=200)),
                ('stir', models.CharField(max_length=14)),
                ('director', models.CharField(blank=True, max_length=200)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('region', models.CharField(max_length=100)),
                ('district', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('active', 'Faol'), ('slow', 'Sekin'), ('inactive', 'Nofaol')], default='active', max_length=20)),
                ('reliability_score', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('monthly_volume', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_lifetime_volume', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('last_order_at', models.DateTimeField(blank=True, null=True)),
                ('credit_limit', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('outstanding_balance', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('growth_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_stores', to='supplier_portal.suppliercompany')),
            ],
            options={
                'db_table': 'supplier_portal_store',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='PaymentRecord',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invoice_number', models.CharField(max_length=50)),
                ('store_name', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('invoice_date', models.DateField()),
                ('due_date', models.DateField()),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('paid', "To'langan"), ('overdue', "Muddati o'tgan"), ('partial', 'Qisman')], default='pending', max_length=20)),
                ('method', models.CharField(blank=True, choices=[('click', 'Click'), ('payme', 'Payme'), ('bank', 'Bank'), ('cash', 'Naqd')], max_length=20)),
                ('days_overdue', models.IntegerField(default=0)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='supplier_portal.outgoinginvoice')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='supplier_portal.suppliercompany')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='supplier_portal.supplierstore')),
            ],
            options={
                'db_table': 'supplier_portal_payment',
                'ordering': ('-days_overdue',),
            },
        ),
        migrations.AddField(
            model_name='outgoinginvoice',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='supplier_portal.supplierstore'),
        ),
        migrations.AddField(
            model_name='incomingorder',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_orders', to='supplier_portal.supplierstore'),
        ),
        migrations.CreateModel(
            name='DeliveryRouteStop',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('store_name', models.CharField(max_length=200)),
                ('eta', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('delivered', 'Yetkazildi')], default='pending', max_length=20)),
                ('order_index', models.IntegerField(default=0)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='supplier_portal.deliveryroute')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='route_stops', to='supplier_portal.supplierstore')),
            ],
            options={
                'db_table': 'supplier_portal_route_stop',
                'ordering': ('order_index',),
            },
        ),
        migrations.AddIndex(
            model_name='supplierproduct',
            index=models.Index(fields=['supplier', 'category'], name='supplier_po_supplie_807680_idx'),
        ),
        migrations.AddIndex(
            model_name='supplierproduct',
            index=models.Index(fields=['supplier', 'name'], name='supplier_po_supplie_9e4459_idx'),
        ),
        migrations.AddIndex(
            model_name='demandsignal',
            index=models.Index(fields=['supplier', 'region'], name='supplier_po_supplie_0f5ed7_idx'),
        ),
        migrations.AddIndex(
            model_name='demandsignal',
            index=models.Index(fields=['supplier', 'hotness'], name='supplier_po_supplie_e82fd5_idx'),
        ),
        migrations.AddIndex(
            model_name='supplierstore',
            index=models.Index(fields=['supplier', 'status'], name='supplier_po_supplie_1322f6_idx'),
        ),
        migrations.AddIndex(
            model_name='supplierstore',
            index=models.Index(fields=['supplier', '-last_order_at'], name='supplier_po_supplie_7acf50_idx'),
        ),
        migrations.AddIndex(
            model_name='supplierstore',
            index=models.Index(fields=['supplier', '-monthly_volume'], name='supplier_po_supplie_4c8088_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='supplierstore',
            unique_together={('supplier', 'stir')},
        ),
        migrations.AddIndex(
            model_name='paymentrecord',
            index=models.Index(fields=['supplier', 'status'], name='supplier_po_supplie_e61f3d_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentrecord',
            index=models.Index(fields=['supplier', '-days_overdue'], name='supplier_po_supplie_f5b959_idx'),
        ),
        migrations.AddIndex(
            model_name='outgoinginvoice',
            index=models.Index(fields=['supplier', '-created_at'], name='supplier_po_supplie_fe1f0a_idx'),
        ),
        migrations.AddIndex(
            model_name='outgoinginvoice',
            index=models.Index(fields=['status', 'supplier'], name='supplier_po_status_2a1cbd_idx'),
        ),
        migrations.AddIndex(
            model_name='incomingorder',
            index=models.Index(fields=['supplier', 'status'], name='supplier_po_supplie_c69047_idx'),
        ),
        migrations.AddIndex(
            model_name='incomingorder',
            index=models.Index(fields=['supplier', '-requested_at'], name='supplier_po_supplie_41735f_idx'),
        ),
    ]
