# Generated by Django 5.2.14 on 2026-05-21 11:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor_snapshot', models.JSONField(default=dict)),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('approve', 'Approve'), ('reject', 'Reject'), ('auth', 'Auth'), ('view', 'View'), ('system', 'System')], max_length=20)),
                ('object_type', models.CharField(max_length=30)),
                ('object_id', models.CharField(max_length=64)),
                ('object_label', models.CharField(blank=True, max_length=300)),
                ('details', models.TextField(blank=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to='tenants.store')),
            ],
            options={
                'db_table': 'audit_entry',
                'ordering': ('-timestamp',),
                'indexes': [models.Index(fields=['store', '-timestamp'], name='audit_entry_store_i_e3dab2_idx'), models.Index(fields=['object_type', 'object_id'], name='audit_entry_object__d8644d_idx'), models.Index(fields=['actor', '-timestamp'], name='audit_entry_actor_i_ad07d6_idx')],
            },
        ),
    ]
